### ISSUE TITLE
[BUG] Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by justjoolz** [muttoni/contract-browser#17]
### Current Behavior

Application error: a client-side exception has occurred (see the browser console for more information).

### Expected Behavior

no error

### Steps To Reproduce

https://contractbrowser.com/A.f233dcee88fe0abe.FungibleTokenMetadataViews

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by muttoni** [comment]
Fixed in [3038e80](https://github.com/muttoni/contract-browser/commit/3038e8032a0bd2062248e653b3aaeea59a269079)! Thanks for flagging!
