### ISSUE TITLE
[BUG] Empty staging issues alert for system contracts

### ISSUE THREAD

**Issue by turbolent** [muttoni/contract-browser#18]
### Current Behavior

Looking at a system contract, like `FlowToken` at https://contractbrowser.com/A.1654653399040a61.FlowToken, shows an empty staging issues alert:

<img width="1456" alt="Screenshot 2024-07-30 at 11 05 22 AM" src="https://github.com/user-attachments/assets/aa83cc2a-94cc-4ee3-bbed-d8fe2491e1d2">

### Expected Behavior

No alert shown.

https://github.com/muttoni/contract-browser/blob/3038e8032a0bd2062248e653b3aaeea59a269079/app/(platform)/%5BcontractId%5D/page.tsx#L70-L80 should probably only show the alert if there is a result and it is a failure, instead of only not showing it for an existing success.

### Steps To Reproduce

See link above

### Environment

```markdown
Any
```

**Comment by muttoni** [comment]
Forgot to reply here! This has been fixed

**Comment by turbolent** [comment]
Great, thank you!
