### ISSUE TITLE
[BUG] Incorrect .find slug / redirect URL

### ISSUE THREAD

**Issue by bartolomej** [muttoni/contract-browser#4]
### Current Behavior

When a wallet has a .find record, its name is shown in the top dropdown. But when you click on the name, the link is incorrect.

### Expected Behavior

In this case, it should lead to flowser.find (https://find.xyz/flowser), instead of https://find.xyz/Flowser%20team.

<img width="289" alt="Screenshot 2023-12-10 at 21 30 49" src="https://github.com/muttoni/contract-browser/assets/36109955/3582e499-8ac2-440a-b379-807bda9375e9">

### Steps To Reproduce

Click on the .find link in the top dropdown (for wallets with an existing .find record)

**Comment by muttoni** [comment]
The reason is it uses the profile name, not the id! thanks for flagging, will fix. Sorry I only just saw this one.

**Comment by muttoni** [comment]
Fixed in https://github.com/muttoni/contract-browser/commit/7aa56d7c0be91e218c311711eab231f07b044b73
