### ISSUE TITLE
[FEATURE] Show flow-cli install command in contract overview

### ISSUE THREAD

**Issue by bartolomej** [muttoni/contract-browser#7]
### Issue to be solved

Flow CLI now ships with a Cadence dependency manager: https://developers.flow.com/tools/flow-cli/dependency-manager

This simplifies and standardizes dependency management in Flow projects, so I think we should update the UI to show the corresponding Flow CLI command in the contract overview page.

### Suggest A Solution

I imagine we would add a piece of UI that shows the auto-generated install command, similar to other package registries like [npm](https://www.npmjs.com/package/@onflow/fcl) or [crates.io](https://crates.io/crates/syn):

<img width="1197" alt="Screenshot 2024-05-15 at 13 06 30" src="https://github.com/muttoni/contract-browser/assets/36109955/e803fe60-bbdd-453b-8f0f-49aab1a9decb">

<img width="995" alt="Screenshot 2024-05-15 at 13 06 47" src="https://github.com/muttoni/contract-browser/assets/36109955/923ea844-714b-4100-b1c3-2ea82e51ff49">

**Comment by muttoni** [comment]
That's a great idea - do you have ideas on what the UX could be like and where to show this?

**Comment by muttoni** [comment]
I think the "code" button is helpful, and think the others are too in case people are old-school. But yeah, I agree with this. I've added a dedicated section right underneath:

![image](https://github.com/muttoni/contract-browser/assets/27052451/f090bdc5-a202-432f-8f3a-21d0cc440228)

**Comment by muttoni** [comment]
This has now been published as part of https://github.com/muttoni/contract-browser/commit/3e44c9cab1c52c473277e3a19e52c53f2ac767bc

**Comment by bartolomej** [comment]
Wow great work, this is awesome! Closing this as it's completed.
